name: CI

on:
  push:
    tags:
      - "v*.*.*"

env:
  GOARCH: arm64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v3

      - name: Install dapper
        run: |
          curl -sL https://releases.rancher.com/dapper/latest/dapper-$(uname -s)-$(uname -m) > /usr/local/bin/dapper
          chmod +x /usr/local/bin/dapper

      - name: Run dapper
        run: |
          dapper ci
          cp -r ./bin/* ./

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            tykio/prometheus-auth
          tags: type=semver,pattern=v{{version}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./package/Dockerfile
          build-args: |
            ARCH=${{ env.GOARCH }}
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
